### ISSUE TITLE
Activiti 翻译错误  15.15.7. 为一个组添加一个成员 Add a member to a group 

### ISSUE THREAD

**Issue by cnsyear** [TKJohn/TKJohn.github.io#1]
15.15.7. 为一个组添加一个成员 Add a member to a group
JSON体：
{
   "user":"kermit"
}

翻译错误正确应为
{
   "userId":"kermit"
}

**Comment by TKJohn** [comment]
感谢反馈

我没有尝试运行，但从[代码](https://github.com/Activiti/Activiti/blob/activiti-5.22.0/modules/activiti-rest/src/main/java/org/activiti/rest/service/api/identity/MembershipRequest.java)看起来应该的确是`userId`。

不过[官方原文](https://github.com/Activiti/Activiti/blob/activiti-5.22.0/userguide/src/en/ch14-REST.adoc) 也是
```json
{
"user":"kermit"
}
```

先修改源文件，发布一次还是有点麻烦 😆
